apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: kafka-robot-actor
  name: kafka-robot-actor
  namespace: kafka-robot-actors
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-robot-actor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-robot-actor
    spec:
      containers:
      - image: tbaums/kafka-robot-actor:latest
        imagePullPolicy: Always
        name: kafka-robot-actor
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 1
