
apiVersion: v1
kind: Service
metadata:
  name: prediction-api-svc
  namespace: mt
spec:
  type: ClusterIP
  selector:
    app: prediction-api
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: prediction-api
  name: prediction-api
  namespace: mt
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prediction-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      containers:
      - image: tbaums/prediction-api:latest
        imagePullPolicy: Always
        name: prediction-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: KF_SERVING_ENDPOINT
          value: "http://mnist-predictor-default.mt.svc.cluster.local/v1/models/mnist:predict"
        - name: PYTHONUNBUFFERED
          value: "1"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 1
status: {}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: prediction-api-ingress
  namespace: mt
spec:
  rules:
  - http:
      paths:
      - path: /prediction-api
        backend:
          serviceName: prediction-api-svc
          servicePort: 8080
